### PR TITLE
Aligning Solution Cards In Leaderboard To Center.

### PR DESCRIPTION
**Pull request by Meet1103**
Aligning Solution Cards In Leaderboard To Center And Removing Console Log Statement From Leaderboard Component.

### CODE REVIEW

**Comment by abdus** [comment]
Screenshot from 2019-11-29 19-16-30
@Meet1103  this should be in a single line, I think. (It's splitting in multiple lines).

Like this: (from previous build)
Screenshot from 2019-11-29 19-19-19

**Comment by Meet1103** [comment]
@thisisabdus I had not made any changes to that file , you can see the commit too.

**Comment by abdus** [comment]
Okay, merging it now. If you intend to fix that, feel free to open a new PR!

**Comment by Meet1103** [comment]
But its same as previous build.
AOC

**Pull request merged**
